### PR TITLE
Added a gulp build process to construct and test the database scripts

### PR DESCRIPTION
**Pull request by spatte21**
This pull request fixes issue #1.

I've added a build folder that contains a gulp project to build and test the database (gulp is a node build tool).  To set it up (having checked out this branch) go to the _build_ folder and run npm install to download the dependencies.

You can run the following 3 builds:

`gulp create-script`

This will result in a create-database.sql script in the _new_ folder (i.e. the root of the schema files)

`gulp run-script` also just `gulp` as its the default

This will create the script and then test it by running against a specified host.  Any failures in the script will be reported in the build results.  If successful the database will remain after the build completes.  **This step will drop any existing database with the same name (see command line parameters below).**

`gulp clean`

This removes the database and the script.

To specify database settings, supply the following parameters:

`--user` the user to run the script as (mandatory for the run-script and clean tasks)
`--password` the password to use (optional, leaving it out implies a blank password)
`--host` the mySql host (optional, defaults to 127.0.0.1)
`--database` the database to create when testing (optional, defaults to test_drinkon)

### CODE REVIEW

**Comment by spatte21** [comment]
Bugger, forgot to reference the issue in my commit message :-(

**Comment by timharris123** [comment]
To get this working on Ubuntu 14.04 I had to add

apt-get install nodejs-legacy (the node command is renamed nodejs in 14.04, this package aliases back to node)

npm install -g gulp (after running the npm install from the build folder or I just kept getting no command [gulp]

**Comment by spatte21** [comment]
I've made the `create-script` task better by allowing you to supply the `--database` command line parameter. If you pass a value then this is used to replace the `%DATABASE%` placeholder, otherwise the placeholder is left.

I'll also add your additional pre-reqs to the project description page once we merge this pull request.

**Comment by timharris123** [comment]
Hi Steve

Tested that with and without the parameter and both looked fine.

I've merged, deleted the branch and closed the item.

Cheers
Tim

**Pull request merged**
